repos:
  - repo: local
    hooks:
      - id: fmt
        name: Format Rust code
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: Clippy linting
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: test
        name: Run tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false

      - id: check
        name: Check Rust code
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

  # Additional quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict